// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateRequest(arg1) {
  return window['go']['bindings']['AIBinding']['GenerateRequest'](arg1);
}

export function GetHistory() {
  return window['go']['bindings']['AIBinding']['GetHistory']();
}

export function Startup(arg1) {
  return window['go']['bindings']['AIBinding']['Startup'](arg1);
}
