// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['bindings']['AIBinding']['DeleteCollection'](arg1);
}

export function GenerateCollection(arg1, arg2) {
  return window['go']['bindings']['AIBinding']['GenerateCollection'](arg1, arg2);
}

export function GenerateRequest(arg1) {
  return window['go']['bindings']['AIBinding']['GenerateRequest'](arg1);
}

export function GetCollectionItemPage(arg1, arg2, arg3) {
  return window['go']['bindings']['AIBinding']['GetCollectionItemPage'](arg1, arg2, arg3);
}

export function GetCollectionItems(arg1) {
  return window['go']['bindings']['AIBinding']['GetCollectionItems'](arg1);
}

export function ListCollections() {
  return window['go']['bindings']['AIBinding']['ListCollections']();
}

export function Startup(arg1) {
  return window['go']['bindings']['AIBinding']['Startup'](arg1);
}
