// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {ports} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function DeleteCollection(arg1:number):Promise<void>;

export function GenerateCollection(arg1:string,arg2:string):Promise<domain.AICollection>;

export function GenerateRequest(arg1:string):Promise<ports.AIGenerateResponse>;

export function GetCollectionItemPage(arg1:number,arg2:number,arg3:number):Promise<bindings.CollectionPageResult>;

export function GetCollectionItems(arg1:number):Promise<Array<domain.AICollectionItem>>;

export function ListCollections():Promise<Array<domain.AICollection>>;

export function Startup(arg1:context.Context):Promise<void>;
