// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ports} from '../models';
import {domain} from '../models';
import {context} from '../models';

export function GenerateRequest(arg1:string):Promise<ports.AIGenerateResponse>;

export function GetHistory():Promise<Array<domain.AIHistory>>;

export function Startup(arg1:context.Context):Promise<void>;
