// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function ExecuteRequest(arg1:string,arg2:string,arg3:string):Promise<domain.APIRequest>;

export function Startup(arg1:context.Context):Promise<void>;
