// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteRequest(arg1:number):Promise<void>;

export function GetRequestHistory():Promise<Array<domain.APIRequest>>;

export function Startup(arg1:context.Context):Promise<void>;
