// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['bindings']['DatabaseBinding']['ClearHistory']();
}

export function DeleteRequest(arg1) {
  return window['go']['bindings']['DatabaseBinding']['DeleteRequest'](arg1);
}

export function GetRequestHistory() {
  return window['go']['bindings']['DatabaseBinding']['GetRequestHistory']();
}

export function Startup(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Startup'](arg1);
}
