// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['bindings']['DbManagerBinding']['AddConnection'](arg1);
}

export function Connect(arg1) {
  return window['go']['bindings']['DbManagerBinding']['Connect'](arg1);
}

export function DescribeTable(arg1, arg2) {
  return window['go']['bindings']['DbManagerBinding']['DescribeTable'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['bindings']['DbManagerBinding']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['bindings']['DbManagerBinding']['ExecuteQuery'](arg1);
}

export function GetActiveConnection() {
  return window['go']['bindings']['DbManagerBinding']['GetActiveConnection']();
}

export function IsConnected() {
  return window['go']['bindings']['DbManagerBinding']['IsConnected']();
}

export function ListConnections() {
  return window['go']['bindings']['DbManagerBinding']['ListConnections']();
}

export function ListDatabases() {
  return window['go']['bindings']['DbManagerBinding']['ListDatabases']();
}

export function ListSchemas() {
  return window['go']['bindings']['DbManagerBinding']['ListSchemas']();
}

export function ListTables(arg1) {
  return window['go']['bindings']['DbManagerBinding']['ListTables'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['bindings']['DbManagerBinding']['RemoveConnection'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['DbManagerBinding']['Startup'](arg1);
}
