// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddConnection(arg1:domain.DbConnection):Promise<domain.DbConnection>;

export function Connect(arg1:string):Promise<void>;

export function DescribeTable(arg1:string,arg2:string):Promise<Array<domain.DbColumn>>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<domain.QueryResult>;

export function GetActiveConnection():Promise<domain.DbConnection>;

export function IsConnected():Promise<boolean>;

export function ListConnections():Promise<Array<domain.DbConnection>>;

export function ListDatabases():Promise<Array<domain.DbDatabase>>;

export function ListSchemas():Promise<Array<domain.DbSchema>>;

export function ListTables(arg1:string):Promise<Array<domain.DbTable>>;

export function RemoveConnection(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
