// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContainerLogs(arg1, arg2) {
  return window['go']['bindings']['DockerBinding']['GetContainerLogs'](arg1, arg2);
}

export function GetContainerStats(arg1) {
  return window['go']['bindings']['DockerBinding']['GetContainerStats'](arg1);
}

export function GetContainers() {
  return window['go']['bindings']['DockerBinding']['GetContainers']();
}

export function GetImages() {
  return window['go']['bindings']['DockerBinding']['GetImages']();
}

export function IsDaemonRunning() {
  return window['go']['bindings']['DockerBinding']['IsDaemonRunning']();
}

export function PullImage(arg1) {
  return window['go']['bindings']['DockerBinding']['PullImage'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['bindings']['DockerBinding']['RemoveContainer'](arg1, arg2);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['bindings']['DockerBinding']['RemoveImage'](arg1, arg2);
}

export function RestartContainer(arg1) {
  return window['go']['bindings']['DockerBinding']['RestartContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['bindings']['DockerBinding']['StartContainer'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['DockerBinding']['Startup'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['bindings']['DockerBinding']['StopContainer'](arg1);
}
