// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GetContainerLogs(arg1:string,arg2:string):Promise<Array<domain.ContainerLog>>;

export function GetContainerStats(arg1:string):Promise<domain.ContainerStats>;

export function GetContainers():Promise<Array<domain.Container>>;

export function GetImages():Promise<Array<domain.ImageInfo>>;

export function IsDaemonRunning():Promise<boolean>;

export function PullImage(arg1:string):Promise<void>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;
