// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVariable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['EnvBinding']['AddVariable'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateEnvironment(arg1) {
  return window['go']['bindings']['EnvBinding']['CreateEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['bindings']['EnvBinding']['DeleteEnvironment'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['bindings']['EnvBinding']['DeleteVariable'](arg1);
}

export function ExecuteRequestWithEnv(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['EnvBinding']['ExecuteRequestWithEnv'](arg1, arg2, arg3, arg4);
}

export function ListEnvironments() {
  return window['go']['bindings']['EnvBinding']['ListEnvironments']();
}

export function SetActiveEnvironment(arg1) {
  return window['go']['bindings']['EnvBinding']['SetActiveEnvironment'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['EnvBinding']['Startup'](arg1);
}

export function UpdateVariable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['EnvBinding']['UpdateVariable'](arg1, arg2, arg3, arg4, arg5);
}
