// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddVariable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<domain.EnvVariable>;

export function CreateEnvironment(arg1:string):Promise<domain.Environment>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteVariable(arg1:string):Promise<void>;

export function ExecuteRequestWithEnv(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.APIRequest>;

export function ListEnvironments():Promise<Array<domain.Environment>>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateVariable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;
