// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting(arg1) {
  return window['go']['bindings']['SettingsBinding']['GetSetting'](arg1);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['bindings']['SettingsBinding']['SaveSetting'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['SettingsBinding']['Startup'](arg1);
}
