name: Wails build

on:
  push:
    tags:
      - "*"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "whaledesk-linux"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "whaledesk-windows"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "whaledesk-mac"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v3
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.26"
